### ISSUE TITLE
sign in issue

### ISSUE THREAD

**Issue by andrclp** [ayastreb/money-tracker#28]
Hi.

On sign in, after adding the code from email, "Synchronizing data, this might take a moment..." never stops. Tried it a few times with Chrome and Firefox.

**Comment by simon511000** [comment]
+1

**Comment by ayastreb** [comment]
Hi,

do you see any errors in the console?

**Comment by andrclp** [comment]
Hi!
What is strange now, with the console open, it logged me in. Below you can see print.

https://ibb.co/C23vcBy

**Comment by LivingWithHippos** [comment]
I have this same issue, can't login anymore (tried on mobile also). Luckily I'm still logged on my laptop

I get this on Chrome
```
utils.js:262 uncaught at nu at nu 
 at f 
 at Cs 
 TypeError: Cannot create property '__enableIdPInitiatedLogin' on string '#access_token=KiPyv-vHY9OQ85KayW5fX7Lqe4NnyAtu&expires_in=86400&token_type=Bearer&state=iiA0rdyp_g2FARX7ZpNnG3AZT3Ut3gCX'
    at ut.validateAuthenticationResponse (https://app.moneytracker.cc/static/js/1.c0532de2.chunk.js:1:425236)
    at ut.parseHash (https://app.moneytracker.cc/static/js/1.c0532de2.chunk.js:1:425099)
    at https://app.moneytracker.cc/static/js/main.2a0429c8.chunk.js:1:115274
    at new Promise (<anonymous>)
    at parseHash (https://app.moneytracker.cc/static/js/main.2a0429c8.chunk.js:1:115245)
    at https://app.moneytracker.cc/static/js/1.c0532de2.chunk.js:1:448393
    at I (https://app.moneytracker.cc/static/js/1.c0532de2.chunk.js:1:448494)
    at N (https://app.moneytracker.cc/static/js/1.c0532de2.chunk.js:1:446404)
    at y (https://app.moneytracker.cc/static/js/1.c0532de2.chunk.js:1:446071)
    at U (https://app.moneytracker.cc/static/js/1.c0532de2.chunk.js:1:450115)
```

Also this in Firefox (I don't really thinks it's related)

`Errore durante il recupero dei sorgenti originali: request failed with status 404 URL sorgente: https://app.moneytracker.cc/home/ubuntu/Projects/money-tracker/node_modules/chartist-plugin-tooltips/scss/chartist-plugin-tooltip.scss`

**Comment by ayastreb** [comment]
Hi,
Thanks! I can reproduce it as well and will try to fix asap!

**Comment by ayastreb** [comment]
Hi,

it should be fixed now, sorry for the trouble!
I did not test the library update properly, will try to come up with some automated integration tests for the future

**Comment by AkshayRao27** [comment]
> Hi,
> 
> it should be fixed now, sorry for the trouble!
> I did not test the library update properly, will try to come up with some automated integration tests for the future

It still doesn't seem to be working for me. I'm trying to sign up and create an account, but I have the same issue on Chrome Windows as well as on Android.

Console from Chrome Windows: 
`index.js:4226 uncaught at gl {error: "server_error", errorDescription: "Unable to configure verification page.", state: "u6g6Y8wF3v_g4s0sGMFitfJsxNzUE~Yr"}error: "server_error"errorDescription: "Unable to configure verification page."state: "u6g6Y8wF3v_g4s0sGMFitfJsxNzUE~Yr"__proto__: Object
(anonymous) @ index.js:4226
P @ utils.js:262
E @ proc.js:245
M @ proc.js:403
s @ proc.js:102
e.cont @ proc.js:117
M @ proc.js:412
s @ proc.js:102
e.cont @ proc.js:117
M @ proc.js:412
s @ proc.js:102
e.cont @ proc.js:117
N @ proc.js:380
w @ proc.js:449
(anonymous) @ proc.js:516
Promise.then (async)
R @ proc.js:515
(anonymous) @ proc.js:584
I @ proc.js:496
N @ proc.js:366
y @ proc.js:314
U @ proc.js:625
I @ proc.js:496
N @ proc.js:366
w @ proc.js:449
a @ proc.js:531
put @ channel.js:88
(anonymous) @ channel.js:190
(anonymous) @ channel.js:216
i @ scheduler.js:20
c @ scheduler.js:63
a @ scheduler.js:35
(anonymous) @ proc.js:553
I @ proc.js:496
N @ proc.js:366
w @ proc.js:449
Promise.then (async)
R @ proc.js:515
(anonymous) @ proc.js:584
I @ proc.js:496
N @ proc.js:366
y @ proc.js:314
L @ proc.js:521
I @ proc.js:495
N @ proc.js:366
w @ proc.js:449
M @ proc.js:412
e.cont @ proc.js:125
N @ proc.js:372
w @ proc.js:449
(anonymous) @ proc.js:584
I @ proc.js:496
N @ proc.js:366
y @ proc.js:314
L @ proc.js:521
I @ proc.js:495
N @ proc.js:366
w @ proc.js:449
M @ proc.js:412
e.cont @ proc.js:125
N @ proc.js:372
y @ proc.js:314
L @ proc.js:521
I @ proc.js:495
N @ proc.js:366
y @ proc.js:314
U @ proc.js:625
I @ proc.js:496
N @ proc.js:366
w @ proc.js:449
a @ proc.js:531
put @ channel.js:88
(anonymous) @ channel.js:190
(anonymous) @ channel.js:216
i @ scheduler.js:20
c @ scheduler.js:63
a @ scheduler.js:35
(anonymous) @ channel.js:215
emit @ channel.js:39
(anonymous) @ middleware.js:74
(anonymous) @ redux.js:463
value @ App.js:21
Ia @ react-dom.production.min.js:5351
Ma @ react-dom.production.min.js:5099
Da @ react-dom.production.min.js:5066
Sa @ react-dom.production.min.js:5001
ta @ react-dom.production.min.js:4927
Fa @ react-dom.production.min.js:5538
qa @ react-dom.production.min.js:5546
$a.render @ react-dom.production.min.js:5737
(anonymous) @ react-dom.production.min.js:5822
Ua @ react-dom.production.min.js:5468
Ka @ react-dom.production.min.js:5821
render @ react-dom.production.min.js:5850
605 @ index.js:17
f @ auth:1
342 @ logo.svg:1
f @ auth:1
a @ auth:1
e @ auth:1
(anonymous) @ main.7b74d892.chunk.js:1
Show 64 more frames`
